# Generated by Django 4.2.16 on 2024-11-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapatransaction',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
