# Generated by Django 5.1.2 on 2024-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='8GB', max_length=10),
        ),
    ]
